Print usage help and add option to hard delete files instead of moving to trash

diff --git a/bin/janitor b/bin/janitor
--- a/bin/janitor
+++ b/bin/janitor
@@ -1,16 +1,21 @@
 #!/usr/bin/env bash
 
 # Define which folder to clean out (default: ~/Downloads)
-export TARGET_DIR=${1:-$HOME/Downloads}
+export TARGET_DIR=$1
 
 # How many days should a file be able to live in the folder? (default: 30)
-export DAYS_TO_KEEP=${2:-30}
+export DAYS_TO_KEEP=$2
 
 # Trash folder to move deleted files to (default: ~/.Trash)
-export TRASH_DIR=${3:-$HOME/.Trash/}
+export TRASH_DIR=$3
 
 # Location to store log files, relative to the Janitor directory (default: logs)
 export LOG_DIR=logs
+
+if [ -z "$TARGET_DIR" -o -z "$DAYS_TO_KEEP" ]; then
+    echo "Minimum 2 arguments required"
+    exit 1
+fi
 
 function clean() {
     if [ $# -eq 0 ]; then
